/**
 * Placeholder indicators.
 *
 * These names exist in the strategy vocabulary but were never implemented in
 * the Dart engine — they all fall through to a single `result = 0.0` branch
 * marked "requires external data" / "requires trained models".
 * Source: euro_trade/lib/services/signal_engine.dart:1464-1562
 *
 * They are ported as-is. Returning anything other than 0 here would change
 * live signal scoring, which the migration explicitly forbids.
 */

import { register } from '../registry.js';

export const PLACEHOLDER_INDICATORS = [
  'smt_divergence',
  'dom',
  'footprint',
  'iceberg_orders',
  'spoofing',
  'neural_network',
  'kalman_filter',
  'lunar_cycle',
  'astro',
  'seasonality',
  'intermarket',
  'market_breadth',
  'advance_decline',
  'microstructure_analysis',
  'smart_tape_reading',
  'latency_arbitrage_analysis',
  'statistical_arbitrage',
  'quantitative_factor_models',
  'risk_parity_analysis',
  'hidden_liquidity_models',
  'liquidity_heatmaps',
  'pca',
  'ica',
  'clustering_analysis',
  'reinforcement_learning_models',
  'deep_learning_pattern_recognition',
  'transformer_based_time_series',
  'bayesian_networks',
  'hidden_markov_models',
  'gaussian_process_regression',
  'cointegration_spread_analysis',
  'cross_asset_flow_analysis',
  'macro_cycle_analysis',
  'economic_calendar_impact_analysis',
  'news_sentiment_analysis',
  'social_sentiment_analysis',
  'on_chain_analysis',
  'funding_rate_analysis',
  'long_short_ratio_analysis',
  'liquidation_heatmap_analysis',
  'options_open_interest_analysis',
  'gamma_exposure',
  'delta_exposure',
  'max_pain_analysis',
  'dealer_positioning_analysis',
  'advance_decline_line',
  'ad_line',
  'mcclellan_oscillator',
  'mcclellan_summation',
  'arms_index',
  'trin',
  'tick_index',
  'tick',
  'put_call_ratio',
  'vix',
  'new_highs_lows',
  'nhnl',
  'breadth_thrust',
  'zweig_breadth',
  'bullish_percent_index',
  'bpi',
  'sector_rotation',
  'relative_rotation_graph',
  'rrg',
  'exchange_netflow',
  'exchange_reserves',
  'hash_rate',
  'mining_difficulty',
  'whale_alert',
  'realized_pnl',
  'sopr',
  'nupl',
  'mvrv',
  'stock_to_flow',
  'pi_cycle',
  'yield_curve',
  'us10y',
  'dxy',
  'gold_ratio',
  'risk_on_off',
  'cot_report',
  'commitment_of_traders',
  'xgboost',
  'random_forest',
  'lstm',
  'transformer',
  'cnn_pattern',
  'autoencoder',
  'som',
  'gradient_boosting',
  'svm_classifier',
  'tcn',
  'wavenet',
] as const;

register([...PLACEHOLDER_INDICATORS], () => 0.0);
